name: CAISO_model
channels:
  - defaults
dependencies:
  - numpy=1.18.1
  - pandas=1.0.3
  - scikit-learn=0.22.1
  - cloudpickle=1.2.2
  - pip=20.0.2
  - itsdangerous==2.0.1
  - pip:
    - mlflow
    - influxdb